# permissions for end users to edit timeseriesdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: timeseriesdb-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: timeseries-operator
    app.kubernetes.io/part-of: timeseries-operator
    app.kubernetes.io/managed-by: kustomize
  name: timeseriesdb-editor-role
rules:
- apiGroups:
  - operator.extend-k8s.io
  resources:
  - timeseriesdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.extend-k8s.io
  resources:
  - timeseriesdbs/status
  verbs:
  - get
